function ...
    [...
        temperature , ...
        Vsound      , ...
        pressure    , ...
        density     , ...
        viscosity     ...
    ] = medium_earth_atmospehre(altitude) 

    % https://www.engineersedge.com/physics/viscosity_of_air_dynamic_and_kinematic_14483.htm
    % density         = 1.225;                % [kg / m^3]
    % kin_viscosity   = 1.48 * 10^(-5);       % [m^2 / s]
    % viscosity       = 1.81 * 10^(-5);       % [kg / m s]    
    % Vsound          = 340;                  % [m / s] 

    viscosity = 1.81 * 10^(-5);       % [kg / m s]
    
    [temperature, Vsound, pressure, density] = atmosisa(altitude);
    res = [temperature, Vsound, pressure, density, viscosity];
end

