function CPM_w = math_CPMw(w)
    ux = w(1);
    uy = w(2);
    uz = w(3);
    CPM_w = [...
        [0, -uz, uy];...
        [uz, 0, -ux];...
        [-uy, ux, 0]...
        ];  
end

%    ux = w_frd_CM_ned(1);
%    uy = w_frd_CM_ned(2);
%    uz = w_frd_CM_ned(3);
%    [...
%        [0, -uz, uy];...
%        [uz, 0, -ux];...
%        [-uy, ux, 0]...
%        ];
