function eulerKinMatrix = math_eulerKinMatrix(phi, theta)    
    eulerKinMatrix = [...
        [ 1,    sin(phi)*tan(theta),    cos(phi)*tan(theta) ]   ; ...
        [ 0,    cos(phi),               -sin(phi)           ]   ; ...
        [ 0,    sin(phi)/cos(theta),    cos(phi)/cos(theta) ]   ; ...
        ];
        
    % det(eulerKinMatrix) = 1 / cos(theta)  => theta = +- pi/2  
    % nose along the vertical line
end
