function Re_xyz_ned = math_euler2dcm(phi, theta, psi, order)  

    Re_n = [...
        [ 1,            0,          0           ]; ...
        [ 0,            +cos(phi),  +sin(phi)   ]; ...
        [ 0,            -sin(phi),  +cos(phi)   ]  ...
    ];
    
    Re_e = [...
        [ +cos(theta),  0,          -sin(theta) ]; ...
        [ 0,            1,          0           ]; ...
        [ +sin(theta),  0,          +cos(theta) ]  ...
    ];
    
    Re_d = [...
        [ +cos(psi),    +sin(psi),  0           ]; ...
        [ -sin(psi),    +cos(psi),  0           ]; ...
        [ 0,            0,          1           ]  ...        
    ];  
    
    if order == 321
        % v_xyz = Re_n * Re_e * Re_d * v_ned
        Re_xyz_ned = Re_n * Re_e * Re_d;
    end
    if order == 123
        % v_xyz = Re_d * Re_e * Re_n * v_ned
        Re_xyz_ned = Re_d * Re_e * Re_n;
    end
end
